### ISSUE TITLE
Finalize "how to run" instructions

### ISSUE THREAD

**Issue by thompson-tyler** [thompson-tyler/canjam#14]
Instructions on how to run your program.

You should submit any extra packages that you used or negotiate with me to get them installed beforehand. That is, we should be able to copy your submission directory and run your program according to your directions. (This may include running other Erlang nodes, so make this clear!)

Make it clear what is your work and what is the work of others.

**Note:** We already have a pretty solid readme with this content, but it should be structured to fit into the final report and make sure it's really, _really_ comprehensive and reliable. I personally had issues with python finding fluidsynth after installing it with homebrew so we need to make sure Mark and the TAs don't have that problem.
I'm thinking we should include multiple installation options. Like a shell script that tries its best to set everything up. Then fall back to instructions on doing it manually with Homebrew. Then finally, maybe the really manual virtual environment I have running on my local, that involves editing `fluidsynth.py` in the virtual environment. I could even try to write a script to manually edit that file

**Comment by sgilfeather** [comment]
@thompson-tyler Lemme know if this is a big ask, but: could you send me your machine specs and the error that you got when Python couldn't find FluidSynth? I can write a shell script that detects your machine type and tries to install FluidSynth with the appropriate package manager.

**Comment by thompson-tyler** [comment]
In trying to recreate my issue I found that it worked just fine! I think I recently updated to python 3.12 which may have solved it because I haven't changed anything else recently. I guess we just gotta stress that you need 3.12 lol
