### ISSUE TITLE
Design Reflection Peer-Peer Portion 

### ISSUE THREAD

**Issue by CeceliaCrumlish** [thompson-tyler/canjam#16]
A reflection on your design. What was the best decision that you made? What would you do differently next time?

For this discuss your Peer-Peer portion of the design. THX!

Start the response with 

###  Peer-Peer Module Part of the Design

**Comment by sgilfeather** [comment]
A little biased to say that peer-to-peer was the best design decision that we made :)

**Comment by sgilfeather** [comment]
Done :)
