### ISSUE TITLE
Create 1 Page CanJam Poster / Promo

### ISSUE THREAD

**Issue by sgilfeather** [thompson-tyler/canjam#17]
Per Mark's instructions: _"Submit a 1-page PDF or PNG named after your project that summarizes your project. This can be used as a small poster or for future course galleries! If you were at a party, and someone asked you “what was your project in concurrent programming about?” what would you say? No more than two paragraphs, and a graphic is welcome."_

We can mark this up in Figma?

**Comment by thompson-tyler** [comment]
Same as #6 ?

**Comment by thompson-tyler** [comment]
Open to doing something more visually interesting but I figure, for sake of time, a PDF with a picture is a good MVP (already done in `canjam.md`

**Comment by sgilfeather** [comment]
You are absolutely correct I just didn't see Cece's work on #6, thank you
