### ISSUE TITLE
1-page Project Summary

### ISSUE THREAD

**Issue by thompson-tyler** [thompson-tyler/canjam#6]
Submit a 1-page PDF or PNG named after your project that summarizes your project. This can be used as a small poster or for future course galleries! If you were at a party, and someone asked you “what was your project in concurrent programming about?” what would you say? No more than two paragraphs, and a graphic is welcome.

**Comment by CeceliaCrumlish** [comment]
# CanJam

<img width="619" alt="Screenshot 2024-04-28 at 3 54 04 PM" src="https://github.com/thompson-tyler/canjam/assets/78366199/c4f2774f-e068-4537-9efa-a9501fe8849c">

### **About**
Canjam is a multiplayer pygame for sharing sounds, and playing on unique synths created using *soundfonts. 

At the start of each game a player will get a randomly generated synth, color, and instrument grid that they will be able to interact with using their mouse. 

Each column on the grid corresponds to a key, and each row corresponds to an octave. The grid will display the players color and play a sound when a player clicks on square. 

Once connected to other players they will be able to see and hear other players' sounds on their grid. CANJAM supports up to 4 players per game. 

### How to play

Once all of the environment requirements have been fulfilled, and packages downloaded. 
- Simply create an instance of Canjam, by running `python3 run.py --name --verbose` , in the main directory. 
- From there other users may join your room using the command `python3 run.py --their_name --join 1234.SOMEONE_WHO_JOINED_THE_ROOM_IPP`

### Other features

- Canjam uses a Peer-Peer server, which means that when players leave a room the rest of the 
players will still be able to stay in the room, and continue to play the game. How Exciting!
- *Soundfont is a technology that uses a sample based synthesis to play MIDI files, essentially providing the user with fonts or different “instruments” to play MIDI notes with. Far-future work on this project will include loading in more sound fonts as choices. 
- Canjam uses the fluid synth library which uses to the synthesizer chip on your computer, so you can interact indirectly with hardware on your very computer!

**Comment by CeceliaCrumlish** [comment]
<img width="680" alt="Screenshot 2024-04-28 at 4 38 02 PM" src="https://github.com/thompson-tyler/canjam/assets/78366199/dbedfc62-d4cc-4b40-b25a-f9cfa7d18eef">

**Comment by CeceliaCrumlish** [comment]
better img

**Comment by thompson-tyler** [comment]
Added to main as `canjam.md`
