### ISSUE TITLE
Final design

### ISSUE THREAD

**Issue by thompson-tyler** [thompson-tyler/canjam#7]
A final refinement of the design, including any changes since the previous iteration and an explanation of why the change occurred.
This section should include at least one diagram (UML-like).
All the elements from the previous documents (initial and refined designs), edited to bring them up to date. Sections that are no longer relevant can be removed.

**Comment by sgilfeather** [comment]
I did a lot of this work in skylar-work! Let me know if you want to add more (it does need the diagrams though).
